LTD-5004-e2e-create-org
uktrade/lite-frontend pull request #1978
Opened 2024-05-23 17:06 UTC by seijihg

https://uktrade.atlassian.net/browse/LTD-5004

2024-05-23 17:13 UTC, seijihg commented on ci.exporter.env
> -MOCK_SSO_USER_EMAIL=lite-ops@digital.trade.gov.uk
I have deleted that so we can log in as a new user and give us more flexibility. Otherwise it will keeps logging in the above user by default.

EXPORTER_TEST_SSO_EMAIL was added so the fixture can pick it up and log in this user when is needed

2024-05-24 12:57 UTC, kevincarrogan commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    response = create_govuk_sso_user()
I feel a little like the name of this function `create_govuk_sso_user` is misleading because I don't think it does that.

2024-05-24 12:57 UTC, kevincarrogan commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        assert False
It's probably better to raise a useful message here instead of just `assert False` as this is going to be hard to debug if/when it fails.

2024-05-24 12:57 UTC, kevincarrogan commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    if "accounts/logout" in driver.current_url:
I'm not really sure what this is doing here. We go to the page and then _something_ happens where it might go somewhere else?

2024-05-30 08:50 UTC, seijihg commented on ui_tests/exporter/features/register_an_organisation.feature
> +    Given I am not signed into LITE but signed into GREAT SSO
thanks removed!

2024-05-30 08:50 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    response = create_govuk_sso_user()
its creating user but it was here already and being used by some places so I will leave it as it is.

2024-05-30 08:51 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        assert False
done thanks

2024-05-30 08:51 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    if "accounts/logout" in driver.current_url:
probably it was left here when I was testing things making sure i was logged out first if I was logged in.

2024-05-31 08:28 UTC, kevincarrogan commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        assert False, "The current URL does not contain 'register-an-organisation'."
I think https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-fail is probably the right thing to use here.

2024-05-31 08:48 UTC, markj0hnst0n approved these changes

2024-05-31 10:48 UTC, saruniitr requested changes
I think it requires changes and may go through few iterations.
I can take a look once it is ready again.

2024-05-31 10:48 UTC, saruniitr commented on ci.exporter.env
> -MOCK_SSO_USER_EMAIL=lite-ops@digital.trade.gov.uk
Does this not break if we are using mock sso?
Is it verified that it is still working as expected?

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/conftest.py
> +    ):
same as above?
Also relying presence of certain strings is not good. If the url changes then this fails.

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/features/register_an_organisation.feature
> +    When I enter my information to register a commercial organisation
This single step is hiding a lot of actions. I think each should perform individual action and this is very open and doesn't convey what is happening.
Eg It is not clear what information user has to enter for commercial organisation (unless you look at the step definition).

By reading the scenario it should be clear what information is entered and what actions are performed. I think this needs breaking down into individual steps.

And I enter organisation name as ""
And I enter EORI number as ""
...

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/features/register_an_organisation.feature
> +    Then I pick an organisation "Commercial organisation"
just like the next step please change it "I choose/select the option"

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/features/register_an_organisation.feature
> +    When I enter my information to register an individual organisation
Same here and the same steps can be reused here.

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    functions.click_submit(driver)
why are we submitting, entering some data and submitting twice again?

There is also phone number that we enter in the form.

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        MockSigninPage(driver).sign_in(fake.email())
Is this the result of deleting `MOCK_SSO_USER_EMAIL` above?
Not sure what is the reason to remove but it is just making things more complicated.

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    if "register-an-organisation" in driver.current_url:
this pattern is used in multiple places and not the correct approach.
When this step is executed then we are expected to be on the correct page, if not test fails as it should be so no need to check again.

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    no = utils.get_element_index_by_text(Shared(driver).get_radio_buttons_elements(), option)
this is not the efficient way to select element as it loops through all elements.
I think we should always go with one of the following variants
```
driver.find_element(by=By.ID, value)
driver.find_element(by=By.CLASS_NAME, value)
driver.find_element(by=By.CSS_SELECTOR, value)
driver.find_element(by=By.XPATH, value)
```

2024-05-31 10:48 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    functions.click_submit(driver)
if we are also submitting then the step should reflect that,

eg "I choose the option "option" and submit

2024-05-31 11:00 UTC, seijihg commented on ci.exporter.env
> -MOCK_SSO_USER_EMAIL=lite-ops@digital.trade.gov.uk
yes its working as expected

2024-05-31 11:59 UTC, seijihg commented on ui_tests/exporter/conftest.py
> +    ):
I can base it on something else, but yea because we are not logging in automatically now it will use exporter_info["email"] to log in.

2024-05-31 12:01 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        MockSigninPage(driver).sign_in(fake.email())
the reason it was removed because to create a new organisation you need to log in as a new user.

2024-05-31 12:07 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    functions.click_submit(driver)
we confirm data and then we in checks data is correct page where we click submit, just reused the same function to click button thats all

2024-05-31 12:09 UTC, seijihg commented on ui_tests/exporter/features/register_an_organisation.feature
> +    When I enter my information to register a commercial organisation
I am not sure if it does matter much, since we are testing if flow of registering is working correctly so things are just random inputs.

2024-05-31 12:16 UTC, saruniitr commented on ui_tests/exporter/features/register_an_organisation.feature
> +    When I enter my information to register a commercial organisation
Random input is fine, it just need to be broken down into individual action instead of one step doing all the actions.
We can say,
"And I enter EORI number"

and in the definition you can enter random EORI number following the format it is expecting.
Similarly for other steps.

2024-05-31 12:22 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    functions.click_submit(driver)
ok it looks like it is submitting multiple times to skip the confirmation screen?
I think this needs to reflect in the test eg with a step saying that I see summary screen with the details validated etc.
This again goes back to doing multiple different actions in a single step.

2024-06-03 09:38 UTC, saruniitr reviewed
I think it is moving in the right direction, few more changes requested and this is good.

2024-06-03 09:38 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    driver.get(exporter_url.rstrip("/") + "/auth/logout")
I think the previous comment is still valid here, what is the purpose of this step?
What is the reason to ensure you are not logged in? when the test start you are. not logged in anyway so we can just proceed to login. Please remove this step.

2024-06-03 09:38 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        MockSigninPage(driver).sign_in(fake.email())
This is the confusing bit and I am not following the need to check this.

`MOCK_SSO_USER_EMAIL` is already deleted above so what is the need to check here?
Also in this step it should not matter whether mock sso endpoints are active or not, this step should just try to sign in. Please remove this condition.

2024-06-03 09:38 UTC, saruniitr commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +        driver.find_element(By.ID, "id_REGISTRATION_TYPE-type_2").click()
this pattern is not encouraged in the tests where step behaves differently based on a condition.
Usually we create separate steps for each option. So in this case you have two options,
- create separate steps for commerical and private individual
- if you want single step then without using condition find the element using the given parameter and select that option.

2024-06-03 09:38 UTC, saruniitr commented on ui_tests/exporter/features/register_an_organisation.feature
> +    Then I enter random site details and finish submitting
I understand we are entering random details but we don't have to specify that in the step, these can be,
```
    When I enter company name
    And I enter company EORI number
    And I enter company SIC number
    And I enter company VAT number
    And I enter company registration number and continue
    And I enter random site details and finish submitting
```

`Then` only at the last step as that defines the outcome of all above steps

2024-06-03 09:38 UTC, saruniitr commented on ui_tests/exporter/conftest.py
> +    ):
As mentioned below in other comment, I am not following the need to check for these here.
`MOCK_SSO_USER_EMAIL` is deleted so what is the need to check again?

2024-06-03 09:38 UTC, saruniitr commented on ci.exporter.env
> -MOCK_SSO_USER_EMAIL=lite-ops@digital.trade.gov.uk
I think deleting this is causing you more issues and various conditions have been added to overcome this.
I am not seeing the need to delete this.

2024-06-04 08:52 UTC, seijihg commented on ci.exporter.env
> -MOCK_SSO_USER_EMAIL=lite-ops@digital.trade.gov.uk
no, without deleting this I cant log in as a new user to test the flow because when the image is being built it will use MOCK_SSO_USER_EMAIL to authenticate automatically on the API side. I cant overwrite this with a command etc. I spent two looooong time on this trying to solve this issue

2024-06-04 08:56 UTC, seijihg commented on ui_tests/exporter/step_defs/test_register_an_organisation.py
> +    driver.get(exporter_url.rstrip("/") + "/auth/logout")
I have added it because at the beginning I was logged in for some reason maybe because of parallel thingy since its using the same container to run chrome.

2024-06-04 11:20 UTC, seijihg commented on ui_tests/exporter/conftest.py
> +    ):
probably there is no need :P just left it there since its the pattern used previously :D

2024-06-04 15:00 UTC, kevincarrogan approved these changes

2024-06-05 08:38 UTC, saruniitr approved these changes

2024-06-05 08:48 UTC, merged