Ltd 924 consignee
uktrade/lite-frontend pull request #217
Opened 2021-06-29 13:03 UTC by dgnball

2021-06-29 13:37 UTC, saruniitr requested changes

2021-06-29 13:37 UTC, saruniitr commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    And I add a party of sub_type: "government", name: "Mr Smith", website: "https://www.smith.com", address: "London" and country "Ukraine"
Please add a step whether we select existing or reuse party (as in above scenario)
`And I answer "No" for whether I want to reuse an existing party`

`And I add a party of sub_type: "government", name: "Mr Smith", website: "https://www.smith.com", address: "London" and country "Ukraine"`
This should also be similar to above otherwise we will have different convention

2021-06-29 13:37 UTC, saruniitr commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    Then download link is present
Is there no consignee summary screen like in above scenario?
`Then I see the end user summary`

End user and consignee are very similar.

Finally, please move consignee test above end user as that is the logical order.
In the application overview section End user comes first but there is a ticket in the backlog to change this order.

2021-06-30 06:50 UTC, saruniitr approved these changes
one minor comment to be addressed otherwise looks good to me.

2021-06-30 06:50 UTC, saruniitr commented on ui_tests/exporter/features/siel_firearm_application.feature
> +  @an_exporter_test
probably forgot to remove this generic tag?

2021-06-30 07:28 UTC, dgnball commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    And I add a party of sub_type: "government", name: "Mr Smith", website: "https://www.smith.com", address: "London" and country "Ukraine"
Ok, it looks more like the 'end user' section now

2021-06-30 07:29 UTC, dgnball commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    Then download link is present
Ok, I have moved the test and added a 'Then I see the consignee summary' section

2021-06-30 07:29 UTC, dgnball commented on ui_tests/exporter/features/siel_firearm_application.feature
> +  @an_exporter_test
yes I did. Removed.

2021-06-30 07:47 UTC, merged