Ltd 926 submit application
uktrade/lite-frontend pull request #222
Opened 2021-07-02 10:11 UTC by alixedi

2021-07-02 12:58 UTC, saruniitr commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    Then I see the application summary
I think we can refer to the rating, end_use using the `<>` syntax here and verify otherwise if we change the values here then it breaks the assert at https://github.com/uktrade/lite-frontend/pull/222/files#diff-f87a545d64b7d553987a9192348e420854cf340b24cea13cc0a06974585866f1R1188

2021-07-02 12:58 UTC, saruniitr commented on ui_tests/exporter/conftest.py
> +    applications.create_standard_application(api_test_client, context, app_data, submit=False)
if we add application type then we can configure `permanent` or `temporary` also, probably need some changes to the data in `create_standard_application` also but for the purpose of this test I think it is fine.

2021-07-06 07:22 UTC, alixedi commented on ui_tests/exporter/conftest.py
> +    applications.create_standard_application(api_test_client, context, app_data, submit=False)
Yes, I want us to fix this but maybe on a different ticket.

2021-07-06 07:57 UTC, dgnball approved these changes

2021-07-06 07:57 UTC, saruniitr commented on ui_tests/exporter/conftest.py
> +    applications.create_standard_application(api_test_client, context, app_data, submit=False)
ok

2021-07-06 08:08 UTC, saruniitr requested changes

2021-07-06 08:08 UTC, saruniitr commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    Then I see the application summary with <clc_rating>,<end_use>,<end_user_name>,<consignee_name>
I think after this we get to declaration page where user need to enter few more details, these are also required for this test because the application is not yet submitted.

2021-07-06 08:26 UTC, alixedi commented on ui_tests/exporter/features/siel_firearm_application.feature
> +    Then I see the application summary with <clc_rating>,<end_use>,<end_user_name>,<consignee_name>
Ah! good point. I will add a step for that.

2021-07-06 10:02 UTC, saruniitr approved these changes
looks good to me

2021-07-06 10:03 UTC, merged