Login redirect fix 2
uktrade/lite-frontend pull request #234
Opened 2021-07-28 12:53 UTC by eadpearce

2021-07-28 14:24 UTC, alixedi commented on core/auth/views.py
> +
Is putting `auth_internal_user` on the base class a good idea?

I think you are having to check for `SERVICE_NAME` because of this.

2021-07-28 14:25 UTC, alixedi requested changes
I think we shouldn't put `auth_internal_user` on the base class that is meant to be generic.

2021-08-03 12:54 UTC, saruniitr commented on caseworker/auth/helpers.py
> +def save_exporter_user_info_to_session(session, data, user_profile):
This is not used. We would also need `ExporterLoginRequiredMixin` isn't it which is where this will be used?

2021-08-16 10:18 UTC, eadpearce commented on caseworker/auth/helpers.py
> +def save_exporter_user_info_to_session(session, data, user_profile):
Good spot. Have removed this now

2021-08-16 10:24 UTC, saruniitr commented on caseworker/auth/helpers.py
> +def save_exporter_user_info_to_session(session, data, user_profile):
:+1:

2021-08-16 10:26 UTC, saruniitr approved these changes
lgtm

2021-08-16 10:55 UTC, alixedi commented
I think we are doing 2 things in this PR. We can talk about the utility and importance of each one of these -

1) The bug - getting `KeyError` on login

This can be resolved by replacing the contents of `caseworker/auth/services.py` with the following -

```
from core import client
from lite_content.lite_internal_frontend import strings
from lite_forms.generators import error_page


def authenticate_gov_user(request, json):
    resp = client.post(request, "/gov-users/authenticate/", json)
    if resp.status_code == 403:
        return error_page(
            request,
            title=strings.Authentication.UserDoesNotExist.TITLE,
            description=strings.Authentication.UserDoesNotExist.DESCRIPTION,
            show_back_link=False,
        )

    elif resp.status_code != 200:
        return error_page(request, show_back_link=False)

    return resp.json(), resp.status_code
```

(I have just taken the code from this PR and placed it in a place that allows me to not have to change a bunch of other things)

2) The refactor that introduced `CaseworkerLoginRequiredMixin`

This may be a good change but without a corresponding `ExporterLoginRequiredMixin`, it seems to add to the confusion.

Now, I am not suggesting that we put in the proposed `ExporterLoginRequiredMixin` in this PR. I am questioning whether putting in `CaseworkerLoginRequiredMixin` makes the code easier to follow for other people - in which case, happy to run with this and also put in `ExporterLoginRequiredMixin` in a following PR.

2021-08-16 10:58 UTC, alixedi reviewed
I think we are doing 2 things in this PR. We can talk about the utility and importance of each one of these -

1) The bug - getting `KeyError` on login

This can be resolved by replacing the contents of `caseworker/auth/services.py` with the following -

```
from core import client
from lite_content.lite_internal_frontend import strings
from lite_forms.generators import error_page


def authenticate_gov_user(request, json):
    resp = client.post(request, "/gov-users/authenticate/", json)
    if resp.status_code == 403:
        return error_page(
            request,
            title=strings.Authentication.UserDoesNotExist.TITLE,
            description=strings.Authentication.UserDoesNotExist.DESCRIPTION,
            show_back_link=False,
        )

    elif resp.status_code != 200:
        return error_page(request, show_back_link=False)

    return resp.json(), resp.status_code
```

(I have just taken the code from this PR and put it in a place that lets us get away without having to make big changes)

2) The refactor that introduced `CaseworkerLoginRequiredMixin` 

This may be a good change but without a corresponding `ExporterLoginRequiredMixin`, it seems to add to the confusion.

Now, I am not suggesting that we put in the proposed `ExporterLoginRequiredMixin` in this PR. I am questioning whether putting in `CaseworkerLoginRequiredMixin` makes the code easier to follow for other people?

If Yes, happy to run with this and also put in `ExporterLoginRequiredMixin` in a following PR.

If No, can we please just change `authenticate_gov_user `?

2021-08-16 12:10 UTC, eadpearce commented
@alixedi 
> This can be resolved by replacing the contents of `caseworker/auth/services.py` with the following -
> 
> ```
> from core import client
> from lite_content.lite_internal_frontend import strings
> from lite_forms.generators import error_page
> 
> 
> def authenticate_gov_user(request, json):
>     resp = client.post(request, "/gov-users/authenticate/", json)
>     if resp.status_code == 403:
>         return error_page(
>             request,
>             title=strings.Authentication.UserDoesNotExist.TITLE,
>             description=strings.Authentication.UserDoesNotExist.DESCRIPTION,
>             show_back_link=False,
>         )
> 
>     elif resp.status_code != 200:
>         return error_page(request, show_back_link=False)
> 
>     return resp.json(), resp.status_code
> ```
> 
> (I have just taken the code from this PR and put it in a place that lets us get away without having to make big changes)

I didn't want to do this because [this line](https://github.com/uktrade/lite-frontend/blob/master/core/auth/views.py#L57) is expecting 2 values to be returned by `authenticate_gov_user` and I wanted to keep the changes as small as possible without it turning into a very big refactor that, as we've seen previously, will probably break things that we weren't expecting. Sticking to just adding `CaseworkerLoginRequiredMixin` in this PR can de-risk that and if everything seems fine we can add the corresponding `ExporterLoginRequiredMixin` in a separate PR

2021-08-17 08:43 UTC, alixedi approved these changes

2021-08-17 08:48 UTC, merged