Fix bug in case detail.
uktrade/lite-frontend pull request #270
Opened 2021-10-13 09:21 UTC by alixedi

2021-10-13 13:23 UTC, saruniitr requested changes

2021-10-13 13:23 UTC, saruniitr commented on caseworker/advice/forms.py
> +    )
Assuming this is a placeholder? designs show refusal criteria and refusal reasons

2021-10-14 13:34 UTC, alixedi commented on caseworker/advice/forms.py
> +            label='Select all <a href="/">refusal criteria</a> that apply',
Anyone knows what is the URL for this?

2021-10-14 13:34 UTC, alixedi commented on caseworker/advice/forms.py
> +            help_text='<a href="/">Choose a refusal reason from the template list</a>',
Anyone knows what is the URL for this?

2021-10-14 14:36 UTC, merged