LTD-1345: Select advice approval, refusal, footnotes text from picklists
uktrade/lite-frontend pull request #319
Opened 2021-12-02 15:13 UTC by saruniitr

## Change description
Add option to select advice approval, refusal, footnote text from picklists (list of user defined text blocks).

Approve, Refuse advice forms are updated to use picklists

2021-12-02 15:17 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +    $("a[target={{ target }}]").click(function () {
When the link on the form is clicked, this gets called and brings up the Modal to select a picklist item

2021-12-02 15:18 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +    function setTextareaValue(textareaId) {
this is updated the target text field with the text from the selected picklist item

2021-12-02 15:52 UTC, alixedi commented on caseworker/advice/templates/advice/picklist.html
> +    $("a[target={{ target }}]").click(function () {
@saruniitr Might be better to have a single `js` function defined separately and call it with the target as an argument here. Something like -

```
$("a[target={{ target }}]").click(picklist({{ target }}))
```

Whereas, separately -

```
def picklist(target) {
    LITECommon.Modal.....
}
```

2021-12-02 16:00 UTC, wkeeling commented on caseworker/advice/forms.py
> +        widget=forms.Textarea(attrs={"rows": "10", "style": "margin-top:20px"}),
I'm wondering if using a fixed pixel `margin-top` here is going to cause problems on other types of devices - e.g. mobile?

2021-12-02 16:15 UTC, saruniitr commented on caseworker/advice/forms.py
> +        widget=forms.Textarea(attrs={"rows": "10", "style": "margin-top:20px"}),
good point, I will have a quick search and replace accordingly.

2021-12-02 16:50 UTC, saruniitr commented on caseworker/advice/forms.py
> +        widget=forms.Textarea(attrs={"rows": "10", "style": "margin-top:20px"}),
@wkeeling there is a govuk class, I have updated to use that class

2021-12-03 09:22 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +    $("a[target={{ target }}]").click(function () {
Anonymous function is moved into a separate function

2021-12-03 11:25 UTC, wkeeling approved these changes

2021-12-03 13:40 UTC, alixedi requested changes

2021-12-03 13:40 UTC, alixedi commented on caseworker/advice/forms.py
> +        help_text='<a class="govuk-link govuk-link--no-visited-state" href="#" target="approval_reasons">Choose an approval reason from the template list</a>',
Can we not subclass `CharField` so that we don't have to put the `help_text` incantation every time for `picklist` inputs?

Something like -

```
class PicklistCharField(forms.CharField):
    def __init__(self, target, *args, **kwargs):
        help_text = f'<a class="govuk-link govuk-link--no-visited-state" href="#" target="{target}">Choose an approval reason from the template list</a>'
        super.__init__(*args, **kwargs, help_text=)
```

2021-12-03 13:40 UTC, alixedi commented on caseworker/advice/templates/advice/picklist.html
> +    function showPickListItems(event) {
The reason I asked you to put this in a separate function was so that this bit is not repeated 3 times on the rendered page. 

ATM, whenever you do -

```
{% include "advice/picklist.html" with target="approval_reasons" picklist_type="standard_advice" picklist_name="Standard Advice" %}
```

It copies over everything in this template (including this function) into the rendered template. This should be fixable by moving the function to another template and including it once.

2021-12-03 13:52 UTC, alixedi commented on caseworker/advice/templates/advice/picklist.html
> +            filter{{ target }}PicklistItems(true, $(this).val());
Can we not replace this with -

```
def FilterPicklistItems(true, $(this).val(), target)
```

The fact that we are choosing to template a function where can just pass arguments doesn't make sense.

2021-12-03 16:24 UTC, saruniitr commented on caseworker/advice/forms.py
> +        help_text='<a class="govuk-link govuk-link--no-visited-state" href="#" target="approval_reasons">Choose an approval reason from the template list</a>',
:+1:

2021-12-03 16:25 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +            filter{{ target }}PicklistItems(true, $(this).val());
moved this into a template and only included once now so no repetition and not templating the function.

2021-12-03 16:26 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +    function showPickListItems(event) {
Moving this function to a template is not bringing up the modal when the link is clicked.

2021-12-04 02:29 UTC, saruniitr commented on caseworker/advice/templates/advice/picklist.html
> +    function showPickListItems(event) {
repetition is avoided now

2021-12-06 10:33 UTC, alixedi approved these changes
One comment that I will leave with you. 

A reminder that we will need to add browser tests for this later. Because of all the `js`.

2021-12-06 10:33 UTC, alixedi commented on caseworker/advice/forms.py
> +    def __init__(self, picklist_attrs, label, help_text, required=True, min_rows=10, **kwargs):
I think we can remove `required` and `min_rows` from here, no? Because you are passing through `kwargs` to super and these would be included without having to put them explicitly in the parameters.

2021-12-06 10:49 UTC, saruniitr commented on caseworker/advice/forms.py
> +    def __init__(self, picklist_attrs, label, help_text, required=True, min_rows=10, **kwargs):
I was expecting the same but when removed django-forms complaining that it received `unexpected keyword argument 'min_rows'`

2021-12-06 10:58 UTC, saruniitr commented on caseworker/advice/forms.py
> +    def __init__(self, picklist_attrs, label, help_text, required=True, min_rows=10, **kwargs):
yeah, I will remove them.

2021-12-06 11:11 UTC, merged