LTD-1607-fix-backlink
uktrade/lite-frontend pull request #412
Opened 2022-01-24 15:59 UTC by depsiatwal

fix back button to approve/refuse advice 

![image](https://user-images.githubusercontent.com/44236490/150818030-39351644-740a-488d-84af-00920b87d68d.png)

2022-01-24 16:26 UTC, sekharpanja approved these changes

2022-01-24 16:35 UTC, saruniitr requested changes
Back link to be corrected is in the template

2022-01-24 16:35 UTC, saruniitr commented on caseworker/advice/views.py
> +        return reverse("cases:select_advice", kwargs=self.kwargs)
the back link to be changed is in the template, previous value of `cases:view_my_advice` is correct here and below as well.

2022-01-25 14:11 UTC, depsiatwal commented
This flag fixes the templates to also show when we in edit mode 

![image](https://user-images.githubusercontent.com/44236490/150992544-957f0ac9-1db5-4ed4-a309-9c5ee31bd567.png)

since this flag was already there I assume it's some how disappeared from the context

2022-01-25 15:32 UTC, saruniitr approved these changes

2022-01-26 09:34 UTC, merged