Ltd 1645 names
uktrade/lite-frontend pull request #424
Opened 2022-02-07 00:27 UTC by seijihg

SS Before:
![image](https://user-images.githubusercontent.com/24960282/152708185-75cda64f-c90b-4f17-b74c-bd225c65c348.png)

SS After:
<img width="958" alt="Screenshot 2022-02-07 at 00 26 46" src="https://user-images.githubusercontent.com/24960282/152708273-637b0c71-194e-4d93-aab7-fd4ea5c7ea0a.png">
<img width="1009" alt="Screenshot 2022-02-07 at 00 26 54" src="https://user-images.githubusercontent.com/24960282/152708275-406011b0-6329-4d7d-8b11-fe9cc0dd584f.png">

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/LTD-1645
- [x] Jira ticket has the correct status.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [x] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2022-02-07 09:58 UTC, depsiatwal commented on caseworker/teams/tests/test_views.py
> +        print(history)
print ???

2022-02-07 09:59 UTC, depsiatwal commented on caseworker/teams/templates/teams/team-edit.html
> +{% endblock %}
CR required here

2022-02-07 10:17 UTC, wkeeling commented on caseworker/teams/forms.py
> +from crispy_forms_gds.layout import Button, Field, Layout, Size
Be good to follow the [standard import order](https://www.python.org/dev/peps/pep-0008/#imports) we (try) to adhere to elsewhere, as in:
```
Standard library imports.
# Blank line
Related third party imports.
# Blank line
Local application/library specific imports.
```
So in this case, the `crispy_forms_gds` imports should be grouped with the 'related third party imports' and should be moved above `django.urls` following alphabetical ordering.

2022-02-07 10:17 UTC, wkeeling commented on caseworker/teams/forms.py
> +
File needs a new line adding at the end.

2022-02-07 10:24 UTC, wkeeling commented on caseworker/teams/views.py
> +        form.fields['name'].initial = team["team"]["name"]
You should be able to override `get_initial()` and return a dictionary of the data for these fields - rather than override `get_form()` itself.

2022-02-07 10:26 UTC, wkeeling commented on caseworker/teams/views.py
> +        form.fields['part_of_ecju'].initial = True if part_of_ecju == True else False
`part_of_ecju` is a boolean, so this can be simplified to:
```python
form.fields['part_of_ecju'].initial = part_of_ecju
```
but also see comment above about doing this in `get_initial()`.

2022-02-07 10:26 UTC, wkeeling commented on caseworker/teams/views.py
> +        form.fields['is_ogd'].initial = True if is_ogd == True else False
Simplify as previous comment.

2022-02-07 10:29 UTC, wkeeling commented on caseworker/teams/views.py
> +        if form.is_valid():
Have a look at the `form_valid()` method for doing this. It probably won't be necessary to override `post()` itself.

2022-02-07 10:29 UTC, wkeeling commented on caseworker/teams/views.py
> +        return super().post(*args, **kwargs)
Missing new line at end of file.

2022-02-07 10:32 UTC, wkeeling commented
For the new field, it may be worth checking with Colin on the wording, as I would imagine "Is this team an OGD?" would make more sense than "Is this team part of OGD?" (OGD stands for "Other Government Department").

2022-02-07 10:33 UTC, wkeeling commented on caseworker/teams/tests/test_views.py
> +import requests_mock
See previous comment about import order.

2022-02-07 10:55 UTC, wkeeling commented on caseworker/teams/tests/test_views.py
> +    with requests_mock.Mocker() as req_mock:
You can specify `requests_mock` as a fixture argument to the test function - no need to define separately.

2022-02-07 11:54 UTC, seijihg commented on caseworker/teams/tests/test_views.py
> +        print(history)
is a draft and test is not finished kinda stuck on it so not much cleaning overall :P

2022-02-07 18:15 UTC, seijihg commented on caseworker/teams/templates/teams/team-edit.html
> +{% endblock %}
what do you mean by CR?

2022-02-09 10:26 UTC, wkeeling commented on caseworker/teams/tests/test_forms.py
> +import pytest
The current convention in the frontend app is that tests live in `unit_tests/caseworker/<app>` so it may be better to move this `test_forms.py` module to e.g. `unit_tests/caseworker/teams/forms/test_edit_team.py` (you'll need to create the destination as it doesn't currently exist).

2022-02-09 10:27 UTC, wkeeling commented on caseworker/teams/tests/test_forms.py
> +def form_team_data():
This common fixture can be moved to `unit_tests/caseworker/conftest.py`.

2022-02-09 10:28 UTC, wkeeling commented on caseworker/teams/tests/test_views.py
> +def form_team_data():
This fixture will no longer be needed since the fixture in `unit_tests/caseworker/conftest.py` can be used (see previous comment).

2022-02-09 10:49 UTC, wkeeling commented on caseworker/teams/forms.py
> +        required=False,
Since the radio choice is mandatory, should this be set to `required=True` (or omitted which means the same)?

2022-02-09 10:53 UTC, wkeeling commented on caseworker/teams/views.py
> +        user, _ = get_gov_user(self.request)  # noqa: F811
Curious to understand why `F811` is needed since flake8 hadn't previously been complaining about these lines? Or is it your IDE that's complaining?

2022-02-09 10:55 UTC, wkeeling commented on caseworker/teams/forms.py
> +        required=False,
Actually I guess the radio will always be checked since the view will have populated with initial data.

2022-02-09 10:59 UTC, wkeeling commented on caseworker/teams/views.py
> +        data_dict = self.request.POST.dict()
Need to use `form.cleaned_data` to retrieve the validated form data - rather than the raw data from the original POST.

2022-02-09 11:02 UTC, wkeeling requested changes
Looks good, but added a few comments inline.

2022-02-09 12:46 UTC, seijihg commented on caseworker/teams/views.py
> +        user, _ = get_gov_user(self.request)  # noqa: F811
its linter in circleCI keeps complaining in PR which I guess it did not before because linter checks got added after this file/part of code was created?

2022-02-09 13:47 UTC, seijihg commented on caseworker/teams/views.py
> +        data_dict = self.request.POST.dict()
ah this is interesting django is full of premade-things.

2022-02-10 11:29 UTC, wkeeling commented on caseworker/teams/templates/teams/team-edit.html
> +{% endblock %}
Just missing a new line

2022-02-10 11:30 UTC, wkeeling requested changes
Looks good - but are you able to squash your commits?

2022-02-11 11:06 UTC, merged