LTD-2465-validate-email-new-user
uktrade/lite-frontend pull request #753
Opened 2022-06-22 10:56 UTC by depsiatwal

2022-06-23 13:23 UTC, alixedi requested changes

2022-06-23 13:23 UTC, alixedi commented on exporter/organisation/members/users/forms.py
> +
Usually, passing `request` into a form is a bad sign but I see what you are trying to do.

Would you consider writing a function in one of them `services.py` that gets all the emails for the `organisation`, passing them into the form instead of `request` and then validating against them?

Also, presume you are trying to check if an element in in a list? Why don't use `set` for this?

2022-06-23 13:28 UTC, kevincarrogan commented on exporter/organisation/members/users/forms.py
> +
Don’t use set either. Use any.

2022-06-24 08:54 UTC, alixedi approved these changes
One minor comment that would elevate this to 🤌

2022-06-24 08:54 UTC, alixedi commented on exporter/core/services.py
> +    return response.json()["results"]
A slight improvement that we can do here is to make this function return the set of emails?

Also perhaps rename it to `get_org_user_emails` to reflect the extra bits?

This would remove this particular logic from the view and might make testing even easier :)

2022-06-24 08:57 UTC, alixedi commented
Also, please clean up your commits before you hit merge @depsiatwal  🙏

2022-06-24 10:06 UTC, merged